name: Ryan McAdams
favicon: null
layout_spectrum: 0.99579
typography_spectrum: 0.2987
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0d19'
    - '#970609'
    - '#c6c6c6'
    - '#5c3c31'
    - '#998a87'
  brandStrength: 0.19919717404991388
  lightness: 0.8543265773914754
  saturation: 0.12420800840482116
  rhythmicContrast: 0.8643728906754404
purpose: []
