name: Ryan McAdams
favicon: null
layout_spectrum: 0.6398742012679577
typography_spectrum: 0.3147377031855285
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.19919717404991388
  lightness: 0.8543265773914754
  saturation: 0.12420800840482116
  rhythmicContrast: 0.8643728906754404
purpose: []
